[workspace]
members = ["janus", "."]

[package]
edition = "2021"
name = "saturnus"
version = "0.1.0"

[dependencies]
clap = {version = "4.2", features = ["derive"]}
console = "0.15.6"
glob = "0.3.1"
md5 = "0.7.0"
peg = "0.8.2"
regex = "1.10.2"
rlua = "0.19.4"

[dev-dependencies]
spectral = "0.6.0"
