[package]
edition = "2021"
name = "runtime"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "0.19.4"

# egui = "0.24.1"
